Employees functionality
DroidsOnRoids/DroidsMap pull request #7
Opened 2017-07-11 13:24 UTC by Dawid-Kliszowski

2017-07-11 13:52 UTC, Haydart requested changes

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeDataInteractor.kt
> +                .child("employees")
proponuję wyciągnąć już jako constant do BaseFirebase, u siebie też muszę zrefactorować

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeDataInteractor.kt
> +    private fun retrieveRoomsList(snapshot: DataSnapshot?): List<EmployeeEntityHolder> =
co to za bezczelne kopiowanie xd

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeImageEndpoint.kt
> +
po co ta pusta linia?

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeImageInteractor.kt
> +
j.w.

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeImageInteractor.kt
> +                .child("employees")
tu też do constów najlepiej

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/api/EmployeeImageInteractor.kt
> +            val downloadingTask = storageQueryNode.child(employeeId + ".jpg").downloadUrl
wydaje mi się, ze firebase nie dodaje inferowanych rozszerzeń do nazw, to może nic nie znaleźć

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/business_logic/EmployeeEntityHolder.kt
> +
newline niepotrzebny

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/business_logic/EmployeeEntityHolder.kt
> +    val employee : EmployeeEntity,
Wydaje mi się, że to nie zostało poddane automatycznej refaktoryzacji stylu - przed dwukropkiem nie powinno być chyba spacji

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/mvp/EmployeeUiModel.kt
> +
j.w.

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/employee/repository/EmployeeRepository.kt
> +        private val employeeDataSource : EmployeeDataEndpoint = EmployeeDataInteractor(),
j.w

2017-07-11 13:52 UTC, Haydart commented on app/src/main/java/pl/droidsonroids/droidsmap/feature/room/api/RoomImagesInteractor.kt
> +            val downloadingTask = storageQueryNode.child(imageId + ".svg").downloadUrl
tu też bym się upewnił, czy działać będzie

2017-07-11 13:52 UTC, Haydart commented on app/src/test/java/pl/droidsonroids/droidsmap/EmployeeRepositoryTest.kt
> +    val employeeDataEndpointMock: EmployeeDataEndpoint = mock()
walnąłbym jako lateinit var, żeby wszystko było inicjalizowane w setUp

2017-07-11 14:17 UTC, Dawid-Kliszowski commented on app/src/test/java/pl/droidsonroids/droidsmap/EmployeeRepositoryTest.kt
> +    val employeeDataEndpointMock: EmployeeDataEndpoint = mock()
Po co, skoro można tutaj?

2017-07-11 16:35 UTC, koral-- commented on app/src/test/java/pl/droidsonroids/droidsmap/EmployeeRepositoryTest.kt
> +        whenever(employeeDataEndpointMock.getAllEmployees())
opcjalnalnie można użyć "nowej", kotlinowej składni `on ... doReturn`: https://github.com/nhaarman/mockito-kotlin sekcja Example

2017-07-12 09:22 UTC, koral-- approved these changes

2017-07-12 12:35 UTC, Haydart approved these changes

2017-07-12 13:24 UTC, merged